import type { Metadata } from "next";
import "./globals.scss";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import {Open_Sans} from "next/font/google";
import ScrollToTop from "@/components/scrollToTop/ScrollToTop";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const openSans = Open_Sans({subsets: ['latin']});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} relative`}>
        <Header />
        {children}
      <Footer />
      <ScrollToTop />
      </body>
    </html>
  );
}
